development: &default
  adapter: postgresql
  database: project_name_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: root
  password: root
test:
  <<: *default
  database: project_name_test

production:
  <<: *default
  database: project_name_production 

staging:
  <<: *default
  database: project_name_staging   